query blocks($first: Int, $after: String, $last: Int, $before: String) {
    blocks(first: $first, after: $after, last: $last, before: $before){
        pageInfo {
           ...PageInfoFields
        }
        edges {
            cursor
            node {
                id
                header{
                    ...HeaderFields
                }
                consensus {
                    ...ConsensusFields
                }
                transactions{
                   ...TransactionFields
                }
            }
        }
        nodes {
            id
            header {
                ...HeaderFields
            }
            consensus {
                ...ConsensusFields
            }
            transactions {
                ...TransactionFields
            }
        }
    }
}