query coins($filter: CoinFilterInput!, $first: Int, $after: String, $last: Int, $before: String) {
    coins(filter: $filter, first: $first, after: $after, last: $last, before: $before){
        pageInfo{
            hasPreviousPage
            hasNextPage
            startCursor
            endCursor
        }
        edges{
            cursor
            node{
                utxoId
                owner
                amount
                assetId
                maturity
                status
                blockCreated
            }
        }
        nodes{
            utxoId
            owner
            amount
            assetId
            maturity
            status
            blockCreated
        }
    }
}