query transactions($first: Int, $after: String, $last: Int, $before: String) {
    transactions(first: $first, after: $after, last: $last, before: $before){
        pageInfo{
            ...PageInfoFields
        }
        edges{
            cursor
            node {
                id
                inputAssetIds
                inputContracts{
                    id
                    bytecode
                    salt
                }
                gasPrice
                gasLimit
                maturity
                txPointer
                isScript
                isCreate
                isMint
                inputs {
                    ...InputFields
                }
                outputs {
                    ...OutputFields
                }
                witnesses
                receiptsRoot
                status {
                    ...TransactionStatusFields
                }
                receipts{
                    ...ReceiptFields
                }
                script
                scriptData
                bytecodeWitnessIndex
                bytecodeLength
                salt
                storageSlots
                rawPayload
            }
        }
        nodes {
            id
            inputAssetIds
            inputContracts{
                id
                bytecode
                salt
            }
            gasPrice
            gasLimit
            maturity
            txPointer
            isScript
            isCreate
            isMint
            inputs {
                ...InputFields
            }
            outputs {
                ...OutputFields
            }
            witnesses
            receiptsRoot
            status {
                ...TransactionStatusFields
            }
            receipts {
                ...ReceiptFields
            }
            script
            scriptData
            bytecodeWitnessIndex
            bytecodeLength
            salt
            storageSlots
            rawPayload
        }
    }
}